### ISSUE TITLE
Different Collection title name 

### ISSUE THREAD

**Issue by Shoaibans** [stores-cedcommerce/Nadine--Internal--May-20-#5]
In collections/all page, the title is coming of products, it should be All Collections.
![image](https://user-images.githubusercontent.com/97726944/168580028-962d1161-1c35-471e-bd40-ace098c9136c.png)

**Comment by ui-harshitverma** [comment]
On which page this title name (products) is coming, share the link over here.

**Comment by ui-harshitverma** [comment]
Here we are showing all product's of collections that's why we are using "Products" heading.
